# Site wide configuration

title: Rossana & Olivier in NZ
description: "Blog about our journey in New Zeland"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //rokiwi.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year/:month/:title/
relative_permalinks: false
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap
  
prose:
  media: "images"


# Site owner
owner:
  name: Wouters	Olivier
#  web: http://mademistakes.com
#  email: michael@mademistakes.com
#  twitter: mmistakes
#  bio: "Just another boring, tattooed, time traveling designer."
# avatar: bio-photo.jpg # 160x160 px image for author byline
#  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
